baseURL = "https://plog.czarpino.com/"
languageCode = "en-us"
title = "Programming Log"
theme = "ghostwriter"
copyright = "Czar Pino"
disqusShortname = "czarpino"

[Privacy]

[Privacy.disqus]
    disable = false

[Author]
    name = "Czar Pino"
    profile = "https://twitter.com/czarpino"

[Taxonomies]
    tag = "tags"

[Params]
    intro = false
    headline = ""
    description = ""
    github = "https://github.com/czarpino"
    gitlab = "https://gitlab.com/czarpino"
    linkedin = "https://linkedin.com/in/czarpino/"
    twitter = "https://twitter.com/czarpino"
    stackoverflow = "https://stackoverflow.com/users/1349295/czar-pino"
    email = "inbox@czarpino.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:filename/"

[[menu.main]]
    name = "Latest"
    url = "/"
    weight = 10

[[menu.main]]
    name = "About"
    url = "https://www.czarpino.com"
    weight = 20

[[menu.main]]
    name = "Privacy"
    url = "/privacy/"
    weight = 30
